/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursework;

import javax.swing.*;

/**
 *
 * @author Shahrukh Kamal Khan - 000998261
 */
public class Menu extends javax.swing.JFrame {

    //BisectionMethod bm = new BisectionMethod();
    //Function fn = new Function();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        methodLabel = new javax.swing.JLabel();
        methodComboBox = new javax.swing.JComboBox();
        functionComboBox = new javax.swing.JComboBox();
        functionLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        x1Label = new javax.swing.JLabel();
        x1Text = new javax.swing.JTextField();
        decimalpLabel = new javax.swing.JLabel();
        decimalpText = new javax.swing.JTextField();
        rootsButton = new javax.swing.JButton();
        startingPointLabel2 = new javax.swing.JLabel();
        x2Text = new javax.swing.JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        menuLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("Numerical Methods to Determine Roots");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        methodLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        methodLabel.setForeground(new java.awt.Color(255, 255, 255));
        methodLabel.setText(" Method");
        methodLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        methodComboBox.setBackground(new java.awt.Color(233, 229, 229));
        methodComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        methodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "Bisection", "Secant", "Newton-Raphson", "Item 4" }));
        methodComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        methodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodComboBoxActionPerformed(evt);
            }
        });

        functionComboBox.setBackground(new java.awt.Color(233, 229, 229));
        functionComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        functionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "x-x^2", "ln(x+1)+1", "e^x-3x" }));
        functionComboBox.setToolTipText("");
        functionComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        functionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functionComboBoxActionPerformed(evt);
            }
        });

        functionLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        functionLabel.setForeground(new java.awt.Color(255, 255, 255));
        functionLabel.setText("Function");
        functionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(methodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(methodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(functionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(functionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(methodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(methodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(functionComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(functionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        x1Label.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        x1Label.setForeground(new java.awt.Color(255, 255, 255));
        x1Label.setText("x1:");
        x1Label.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        x1Text.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        x1Text.setText("0.0");
        x1Text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        x1Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1TextActionPerformed(evt);
            }
        });

        decimalpLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        decimalpLabel.setForeground(new java.awt.Color(255, 255, 255));
        decimalpLabel.setText("No. of decimal places:");
        decimalpLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        decimalpText.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        decimalpText.setText("0");
        decimalpText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        decimalpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalpTextActionPerformed(evt);
            }
        });

        rootsButton.setBackground(new java.awt.Color(233, 229, 229));
        rootsButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rootsButton.setText("Roots!");
        rootsButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        rootsButton.setBorderPainted(false);
        rootsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootsButtonActionPerformed(evt);
            }
        });

        startingPointLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        startingPointLabel2.setForeground(new java.awt.Color(255, 255, 255));
        startingPointLabel2.setText("x2:");
        startingPointLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        x2Text.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        x2Text.setText("0.0");
        x2Text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        x2Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2TextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(rootsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(startingPointLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(x2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(x1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(x1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(decimalpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(decimalpText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(decimalpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(decimalpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x1Label)
                        .addComponent(x1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startingPointLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(rootsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void functionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_functionComboBoxActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_functionComboBoxActionPerformed

    private void methodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodComboBoxActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_methodComboBoxActionPerformed

    private void rootsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootsButtonActionPerformed
        // TODO add your handling code here:

        functionName = (String) functionComboBox.getSelectedItem();
        methodName = (String) methodComboBox.getSelectedItem();

        if (!methodName.equalsIgnoreCase("select") && !functionName.equalsIgnoreCase("select")
                && !x1Text.getText().isEmpty()
                && !x2Text.getText().isEmpty() && !decimalpText.getText().isEmpty()) {

            xlow = Double.parseDouble(x1Text.getText()); // declaring inside loop to avoid run time error 
            xup = Double.parseDouble(x2Text.getText()); // due to empty text field being converted to double
            dplaces = Integer.parseInt(decimalpText.getText());

            if (methodName.equalsIgnoreCase("bisection")) {

                //new Table().setVisible(true);

              BisectionMethod bm = new  BisectionMethod();
              bm.bisection(xlow, xup, dplaces, functionName);

            }
            else if(methodName.equalsIgnoreCase("newton-raphson")) {
              NewtonRaphson nr = new NewtonRaphson();
              nr.newtonR(xlow, dplaces, functionName);
            }
            else if(methodName.equalsIgnoreCase("secant")) {
              Secant s = new Secant();
              s.secant(xlow, dplaces, functionName);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Prompt! \n"
                    + "Please select valid options and enter values properly");

        }

    }//GEN-LAST:event_rootsButtonActionPerformed

    private void x1TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1TextActionPerformed
        // TODO add your handling code here:
        System.out.println(xlow);

    }//GEN-LAST:event_x1TextActionPerformed

    private void x2TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2TextActionPerformed
        // TODO add your handling code here:
        System.out.println(xup);

    }//GEN-LAST:event_x2TextActionPerformed

    private void decimalpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalpTextActionPerformed
        // TODO add your handling code here:
        System.out.println(dplaces);
    }//GEN-LAST:event_decimalpTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });

    }

    //xlow is the starting point or the lower value, xup is the higher value of the range
    //dplaces is number of decimal places
    private double xup, xlow;
    private int dplaces;
    private String methodName, functionName;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel decimalpLabel;
    private javax.swing.JTextField decimalpText;
    private javax.swing.JComboBox functionComboBox;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JComboBox methodComboBox;
    private javax.swing.JLabel methodLabel;
    private javax.swing.JButton rootsButton;
    private javax.swing.JLabel startingPointLabel2;
    private javax.swing.JLabel x1Label;
    private javax.swing.JTextField x1Text;
    private javax.swing.JTextField x2Text;
    // End of variables declaration//GEN-END:variables

    public double getXup() {
        return xup;
    }

    /*public void setXup(double xup) {
     this.xup = xup;
     }*/
    public double getXlow() {
        return xlow;
    }

    /*public void setXlow(double xlow) {
     this.xlow = xlow;
     }*/
    public int getDplaces() {
        return dplaces;
    }

    /*public void setDplaces(int dplaces) {
     this.dplaces = dplaces;
     }*/
    public String getMethodName() {
        return methodName;
    }

    /*public void setMethodName(String methodName) {
     this.methodName = methodName;
     }*/
    public String getFunctionName() {
        return functionName;
    }

    /*public void setFunctionName(String functionName) {
     this.functionName = functionName;
     }*/
    /*
     public javax.swing.JLabel getDecimalpLabel() {
     return decimalpLabel;
     }

     public void setDecimalpLabel(javax.swing.JLabel decimalpLabel) {
     this.decimalpLabel = decimalpLabel;
     }

     public javax.swing.JTextField getDecimalpText() {
     return decimalpText;
     }

     public void setDecimalpText(javax.swing.JTextField decimalpText) {
     this.decimalpText = decimalpText;
     }

     public javax.swing.JComboBox getFunctionComboBox() {
     return functionComboBox;
     }

     public void setFunctionComboBox(javax.swing.JComboBox functionComboBox) {
     this.functionComboBox = functionComboBox;
     }

     public javax.swing.JLabel getFunctionLabel() {
     return functionLabel;
     }

     public void setFunctionLabel(javax.swing.JLabel functionLabel) {
     this.functionLabel = functionLabel;
     }

     public javax.swing.JCheckBoxMenuItem getjCheckBoxMenuItem1() {
     return jCheckBoxMenuItem1;
     }

     public void setjCheckBoxMenuItem1(javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1) {
     this.jCheckBoxMenuItem1 = jCheckBoxMenuItem1;
     }

     public javax.swing.JCheckBoxMenuItem getjCheckBoxMenuItem2() {
     return jCheckBoxMenuItem2;
     }

     public void setjCheckBoxMenuItem2(javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2) {
     this.jCheckBoxMenuItem2 = jCheckBoxMenuItem2;
     }

     public javax.swing.JPanel getjPanel1() {
     return jPanel1;
     }

     public void setjPanel1(javax.swing.JPanel jPanel1) {
     this.jPanel1 = jPanel1;
     }

     public javax.swing.JPanel getjPanel2() {
     return jPanel2;
     }

     public void setjPanel2(javax.swing.JPanel jPanel2) {
     this.jPanel2 = jPanel2;
     }

     public javax.swing.JPanel getjPanel3() {
     return jPanel3;
     }

     public void setjPanel3(javax.swing.JPanel jPanel3) {
     this.jPanel3 = jPanel3;
     }

     public javax.swing.JPopupMenu getjPopupMenu1() {
     return jPopupMenu1;
     }

     public void setjPopupMenu1(javax.swing.JPopupMenu jPopupMenu1) {
     this.jPopupMenu1 = jPopupMenu1;
     }

     public javax.swing.JPopupMenu getjPopupMenu2() {
     return jPopupMenu2;
     }

     public void setjPopupMenu2(javax.swing.JPopupMenu jPopupMenu2) {
     this.jPopupMenu2 = jPopupMenu2;
     }

     public javax.swing.JPopupMenu getjPopupMenu3() {
     return jPopupMenu3;
     }

     public void setjPopupMenu3(javax.swing.JPopupMenu jPopupMenu3) {
     this.jPopupMenu3 = jPopupMenu3;
     }

     public javax.swing.JPopupMenu getjPopupMenu4() {
     return jPopupMenu4;
     }

     public void setjPopupMenu4(javax.swing.JPopupMenu jPopupMenu4) {
     this.jPopupMenu4 = jPopupMenu4;
     }

     public javax.swing.JPopupMenu getjPopupMenu5() {
     return jPopupMenu5;
     }

     public void setjPopupMenu5(javax.swing.JPopupMenu jPopupMenu5) {
     this.jPopupMenu5 = jPopupMenu5;
     }

     public javax.swing.JLabel getMenuLabel() {
     return menuLabel;
     }

     public void setMenuLabel(javax.swing.JLabel menuLabel) {
     this.menuLabel = menuLabel;
     }

     public javax.swing.JComboBox getMethodComboBox() {
     return methodComboBox;
     }

     public void setMethodComboBox(javax.swing.JComboBox methodComboBox) {
     this.methodComboBox = methodComboBox;
     }

     public javax.swing.JLabel getMethodLabel() {
     return methodLabel;
     }

     public void setMethodLabel(javax.swing.JLabel methodLabel) {
     this.methodLabel = methodLabel;
     }

     public javax.swing.JButton getRootsButton() {
     return rootsButton;
     }

     public void setRootsButton(javax.swing.JButton rootsButton) {
     this.rootsButton = rootsButton;
     }

     public javax.swing.JLabel getStartingPointLabel() {
     return startingPointLabel;
     }

     public void setStartingPointLabel(javax.swing.JLabel startingPointLabel) {
     this.startingPointLabel = startingPointLabel;
     }

     public javax.swing.JLabel getStartingPointLabel2() {
     return startingPointLabel2;
     }

     public void setStartingPointLabel2(javax.swing.JLabel startingPointLabel2) {
     this.startingPointLabel2 = startingPointLabel2;
     }

     public javax.swing.JTextField getStartingPointText() {
     return startingPointText;
     }

     public void setStartingPointText(javax.swing.JTextField startingPointText) {
     this.startingPointText = startingPointText;
     }

     public javax.swing.JTextField getStartingPointText2() {
     return startingPointText2;
     }

     public void setStartingPointText2(javax.swing.JTextField startingPointText2) {
     this.startingPointText2 = startingPointText2;
     }
     */
}
